"""Compatibility facade for the split V2 query route modules."""

from __future__ import annotations

from .query_routes import (
    BOOK_READ_SCOPE,
    AccountListResponse,
    AccountResponse,
    AssetListResponse,
    AssetResponse,
    BalanceItemResponse,
    BalanceSnapshotResponse,
    BookListResponse,
    BookOwnerReadAuthorizer,
    BookReadAuthorizer,
    BookResponse,
    CategoryListResponse,
    CategoryResponse,
    CreditCardRelationResponse as CreditCardRelationResponse,
    JournalItemResponse,
    JournalItemWithDescriptionResponse,
    JournalPageResponse,
    JournalPageWithDescriptionsResponse,
    JournalPostingResponse,
    ReportingLineResponse,
    ReportingLinesResponse,
    TransactionDescriptionResponse,
    ImportArchiveExportResponse,
    ImportArchiveListResponse,
    ImportArchiveMetadataResponse,
    ImportArchiveRecordCountsResponse,
    authorize_book_owner_read,
    authorize_book_read,
    create_query_router,
)


__all__ = [
    "BOOK_READ_SCOPE",
    "AccountListResponse",
    "AccountResponse",
    "AssetListResponse",
    "AssetResponse",
    "BalanceItemResponse",
    "BalanceSnapshotResponse",
    "BookListResponse",
    "BookOwnerReadAuthorizer",
    "BookResponse",
    "BookReadAuthorizer",
    "CategoryListResponse",
    "CategoryResponse",
    "JournalItemResponse",
    "JournalItemWithDescriptionResponse",
    "JournalPageResponse",
    "JournalPageWithDescriptionsResponse",
    "JournalPostingResponse",
    "ReportingLineResponse",
    "ReportingLinesResponse",
    "TransactionDescriptionResponse",
    "ImportArchiveExportResponse",
    "ImportArchiveListResponse",
    "ImportArchiveMetadataResponse",
    "ImportArchiveRecordCountsResponse",
    "authorize_book_owner_read",
    "authorize_book_read",
    "create_query_router",
]
