from __future__ import annotations

from typing import Annotated, Any, Protocol

from fastapi import Depends

from .api_dependencies import get_service


class AuditRecorder(Protocol):
    def record_security_failure(self, operation: str, details: dict[str, Any]) -> None: ...


class LedgerRouteService(AuditRecorder, Protocol):
    def capture_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_transactions(self, token, **filters): ...
    def record_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_fx_exchange(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_expense(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_income(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_transaction(self, token, transaction_id: str): ...
    def transaction_snapshot(self, token, transaction_id: str): ...
    def adjust_balance(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def confirm_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reject_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def supersede_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reverse_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reclassify_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def account_balance(self, token, account_id: str, *, include_drafts: bool = False): ...


class CatalogRouteService(AuditRecorder, Protocol):
    def list_assets(self, token, *, status: str | None = "active"): ...
    def list_accounts(self, token, **filters): ...
    def create_account(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_account(self, token, account_id: str): ...
    def update_account_metadata(self, token, account_id: str, payload: dict[str, Any], *, idempotency_key: str): ...
    def account_summary(self, token, **filters): ...
    def category_summary(self, token, *, kind: str | None = None, currency: str | None = None): ...
    def list_users(self, token): ...
    def create_user(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_categories(self, token, **filters): ...
    def find_category_by_path(self, token, *, kind: str, path: str): ...
    def create_category(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def ensure_category_path(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_category(self, token, category_id: str): ...
    def update_book_category(
        self,
        token,
        book_id: str,
        category_id: str,
        payload: dict[str, Any],
        *,
        idempotency_key: str,
    ): ...
    def list_credit_cards(self, token): ...
    def get_credit_card(self, token, account_id: str): ...
    def update_credit_card_profile(self, token, account_id: str, payload: dict[str, Any], *, idempotency_key: str): ...


LedgerService = Annotated[LedgerRouteService, Depends(get_service)]
CatalogService = Annotated[CatalogRouteService, Depends(get_service)]
