from __future__ import annotations

from typing import Annotated, Any, Protocol

from fastapi import Depends

from .api_dependencies import get_service


class AuditRecorder(Protocol):
    def record_security_failure(self, operation: str, details: dict[str, Any]) -> None: ...


class LedgerRouteService(AuditRecorder, Protocol):
    def capture_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_transactions(self, token, **filters): ...
    def record_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_fx_exchange(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_expense(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_income(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_transaction(self, token, transaction_id: str): ...
    def transaction_snapshot(self, token, transaction_id: str): ...
    def adjust_balance(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def confirm_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reject_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def supersede_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reverse_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reclassify_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def account_balance(self, token, account_id: str, *, include_drafts: bool = False): ...


class CatalogRouteService(AuditRecorder, Protocol):
    def list_assets(self, token, *, status: str | None = "active"): ...
    def list_accounts(self, token, **filters): ...
    def create_account(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_account(self, token, account_id: str): ...
    def update_account_metadata(self, token, account_id: str, payload: dict[str, Any], *, idempotency_key: str): ...
    def account_summary(self, token, **filters): ...
    def category_summary(self, token, *, kind: str | None = None, currency: str | None = None): ...
    def list_users(self, token): ...
    def create_user(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_categories(self, token, **filters): ...
    def find_category_by_path(self, token, *, kind: str, path: str): ...
    def create_category(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def ensure_category_path(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_category(self, token, category_id: str): ...
    def update_book_category(
        self,
        token,
        book_id: str,
        category_id: str,
        payload: dict[str, Any],
        *,
        idempotency_key: str,
    ): ...
    def list_credit_cards(self, token): ...
    def get_credit_card(self, token, account_id: str): ...
    def update_credit_card_profile(self, token, account_id: str, payload: dict[str, Any], *, idempotency_key: str): ...


class CounterpartyRouteService(AuditRecorder, Protocol):
    def ensure_counterparty(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_counterparties(self, token, **filters): ...
    def get_counterparty(self, token, counterparty_ref: str): ...


class PaymentInstrumentRouteService(AuditRecorder, Protocol):
    def create_payment_instrument(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_payment_instruments(self, token, **filters): ...
    def resolve_payment_instrument(self, token, instrument_ref: str): ...


class PaymentProfileRouteService(AuditRecorder, Protocol):
    def create_payment_profile(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_payment_profiles(self, token, **filters): ...
    def payment_profile_status(self, token, profile_ref: str): ...
    def record_payment_profile_expense(self, token, payload: dict[str, Any], *, idempotency_key: str): ...


class CredentialRouteService(AuditRecorder, Protocol):
    def list_agent_credentials(self, token): ...
    def issue_agent_credential_command(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def issue_machine_credential_command(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def revoke_credential_command(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def revoke_credential_by_id_command(
        self,
        token,
        credential_id: str,
        payload: dict[str, Any],
        *,
        idempotency_key: str,
    ): ...


class RecurringRouteService(AuditRecorder, Protocol):
    def create_recurring_item(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_recurring_items(self, token, **filters): ...
    def get_recurring_item(self, token, recurring_id: str): ...
    def update_recurring_item(self, token, recurring_id: str, payload: dict[str, Any], *, idempotency_key: str): ...
    def check_recurring_reminders(self, token, **filters): ...
    def generate_recurring_drafts(self, token, payload: dict[str, Any], *, idempotency_key: str, book_id=None): ...


LedgerService = Annotated[LedgerRouteService, Depends(get_service)]
CatalogService = Annotated[CatalogRouteService, Depends(get_service)]
CounterpartyService = Annotated[CounterpartyRouteService, Depends(get_service)]
PaymentInstrumentService = Annotated[PaymentInstrumentRouteService, Depends(get_service)]
PaymentProfileService = Annotated[PaymentProfileRouteService, Depends(get_service)]
CredentialService = Annotated[CredentialRouteService, Depends(get_service)]
RecurringService = Annotated[RecurringRouteService, Depends(get_service)]
