from __future__ import annotations

from typing import Annotated, Protocol

from .base import AuditRecorder, ServiceDependency


class BackofficeRouteService(AuditRecorder, Protocol):
    def require_backoffice(self, token): ...
    def backoffice_books(self): ...
    def backoffice_book_members(self): ...
    def backoffice_accounts(self, **filters): ...
    def backoffice_users(self): ...
    def backoffice_auth_identities(self): ...
    def backoffice_categories(self): ...
    def backoffice_transactions(self, **filters): ...
    def backoffice_recurring_items(self): ...
    def backoffice_audit_events(self): ...


BackofficeService = Annotated[BackofficeRouteService, ServiceDependency]

