from __future__ import annotations

from typing import Annotated, Any, Protocol

from .base import AuditRecorder, ServiceDependency


class CatalogRouteService(AuditRecorder, Protocol):
    def list_assets(self, token, *, status: str | None = "active"): ...
    def list_accounts(self, token, **filters): ...
    def list_ledger_accounts(self, token, **filters): ...
    def get_ledger_account(self, token, account_id: str): ...
    def list_financial_accounts(self, token, **filters): ...
    def get_financial_account(self, token, account_id: str, **options): ...
    def financial_account_balance(self, token, account_id: str): ...
    def create_account(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_account(self, token, account_id: str): ...
    def update_account_metadata(self, token, account_id: str, payload: dict[str, Any], *, idempotency_key: str): ...
    def account_summary(self, token, **filters): ...
    def category_summary(self, token, *, kind: str | None = None, currency: str | None = None): ...
    def list_users(self, token): ...
    def create_user(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_categories(self, token, **filters): ...
    def find_category_by_path(self, token, *, kind: str, path: str): ...
    def create_category(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def ensure_category_path(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_category(self, token, category_id: str): ...
    def update_book_category(
        self,
        token,
        book_id: str,
        category_id: str,
        payload: dict[str, Any],
        *,
        idempotency_key: str,
    ): ...
    def list_credit_cards(self, token): ...
    def get_credit_card(self, token, account_id: str): ...
    def update_credit_card_profile(self, token, account_id: str, payload: dict[str, Any], *, idempotency_key: str): ...


CatalogService = Annotated[CatalogRouteService, ServiceDependency]

