from __future__ import annotations

from typing import Annotated, Any, Protocol

from .base import AuditRecorder, ServiceDependency


class FinanceRouteService(AuditRecorder, Protocol):
    def record_investment_event(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_investment_valuation(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_investment_valuations(self, token, account_id: str): ...
    def investment_performance(self, token, account_id: str, *, as_of: str | None = None): ...
    def create_fund(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def allocate_fund(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def spend_fund(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def upload_attachment(self, token, *, filename: str, mime_type: str, content: bytes, idempotency_key: str): ...
    def record_reconciliation_action(self, token, payload: dict[str, Any], *, idempotency_key: str): ...


FinanceService = Annotated[FinanceRouteService, ServiceDependency]

