from __future__ import annotations

from typing import Annotated, Any, Protocol

from .base import AuditRecorder, ServiceDependency


class LedgerRouteService(AuditRecorder, Protocol):
    def capture_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_transactions(self, token, **filters): ...
    def record_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_fx_exchange(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_expense(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def record_income(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def get_transaction(self, token, transaction_id: str): ...
    def transaction_snapshot(self, token, transaction_id: str): ...
    def adjust_balance(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def confirm_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reject_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def supersede_draft(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reverse_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def reclassify_transaction(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def account_balance(self, token, account_id: str, *, include_drafts: bool = False): ...


LedgerService = Annotated[LedgerRouteService, ServiceDependency]

