from __future__ import annotations

from typing import Annotated, Any, Protocol

from .base import ServiceDependency


class OAuthRouteService(Protocol):
    def list_platform_oauth_clients(self, token) -> list[dict[str, object]]: ...
    def register_platform_oauth_client(self, payload) -> dict[str, object]: ...
    def authorize_platform_oauth_request(self, token, payload) -> dict[str, str]: ...
    def exchange_platform_oauth_token_payload(self, payload: dict[str, Any]) -> dict[str, object]: ...
    def create_platform_device_authorization_request(self, payload, issuer: str) -> dict[str, object]: ...
    def revoke_platform_oauth_token_payload(self, payload: dict[str, Any]) -> dict[str, bool]: ...


OAuthService = Annotated[OAuthRouteService, ServiceDependency]
