from __future__ import annotations

from typing import Annotated, Any, Protocol

from .base import AuditRecorder, ServiceDependency


class RecurringRouteService(AuditRecorder, Protocol):
    def create_recurring_item(self, token, payload: dict[str, Any], *, idempotency_key: str): ...
    def list_recurring_items(self, token, **filters): ...
    def get_recurring_item(self, token, recurring_id: str): ...
    def update_recurring_item(self, token, recurring_id: str, payload: dict[str, Any], *, idempotency_key: str): ...
    def check_recurring_reminders(self, token, **filters): ...
    def generate_recurring_drafts(self, token, payload: dict[str, Any], *, idempotency_key: str, book_id=None): ...


RecurringService = Annotated[RecurringRouteService, ServiceDependency]

