from __future__ import annotations

from typing import Annotated, Protocol

from .base import ServiceDependency


class SystemRouteService(Protocol):
    def system_readiness(self) -> dict[str, object]: ...
    def system_status(self, token, *, include_counts: bool = False) -> dict[str, object]: ...
    def posting_semantics_audit(self, token, *, book_id: str = "book_default") -> dict[str, object]: ...
    def posting_semantics_cutover_plan(self, token, *, book_id: str = "book_default") -> dict[str, object]: ...
    def rewrite_posting_semantics(self, token, *, idempotency_key: str, book_id: str = "book_default") -> dict[str, object]: ...
    def resolve_posting_semantics_reviews(self, token, payload: dict[str, object], *, idempotency_key: str, book_id: str = "book_default") -> dict[str, object]: ...
    def local_dev_session(self) -> dict[str, object]: ...
    def local_dev_token(self) -> dict[str, object]: ...


SystemService = Annotated[SystemRouteService, ServiceDependency]
