"""initial snapshot schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-05-17 15:38:37.215337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('institution_type', sa.String(length=40), nullable=True),
    sa.Column('subtype', sa.String(length=64), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('adjustment_accounts',
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('currency')
    )
    op.create_table('app_state',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.String(length=80), nullable=False),
    sa.Column('storage_key', sa.String(length=180), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('original_filename', sa.String(length=240), nullable=False),
    sa.Column('scanner_status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('actor_type', sa.String(length=40), nullable=False),
    sa.Column('entity_ref', sa.String(length=120), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('primary', sa.String(length=80), nullable=False),
    sa.Column('secondary', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('credentials',
    sa.Column('token_hash', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('actor_type', sa.String(length=40), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.String(length=80), nullable=False),
    sa.Column('jti', sa.String(length=80), nullable=False),
    sa.Column('revoked_at', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('credit_card_profiles',
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('credit_limit', sa.String(length=80), nullable=True),
    sa.Column('available_credit', sa.String(length=80), nullable=True),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('annual_fee', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('drafts',
    sa.Column('draft_id', sa.String(length=80), nullable=False),
    sa.Column('memo', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('draft_id')
    )
    op.create_table('funds',
    sa.Column('fund_id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('allocated', sa.String(length=80), nullable=False),
    sa.Column('spent', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('flow', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('fund_id')
    )
    op.create_table('idempotency_receipts',
    sa.Column('key_hash', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=80), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('replay_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key_hash', 'actor_id', 'operation')
    )
    op.create_table('investment_events',
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.String(length=80), nullable=False),
    sa.Column('memo', sa.String(length=256), nullable=False),
    sa.Column('units', sa.String(length=80), nullable=True),
    sa.Column('nav', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('reconciliation_actions',
    sa.Column('reconciliation_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('reconciliation_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('memo', sa.String(length=256), nullable=False),
    sa.Column('occurred_at', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=256), nullable=False),
    sa.Column('category_id', sa.String(length=80), nullable=True),
    sa.Column('reversed_by', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('draft_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.draft_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postings')
    op.drop_table('draft_postings')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('reconciliation_actions')
    op.drop_table('investment_events')
    op.drop_table('idempotency_receipts')
    op.drop_table('funds')
    op.drop_table('drafts')
    op.drop_table('credit_card_profiles')
    op.drop_table('credentials')
    op.drop_table('categories')
    op.drop_table('audit_events')
    op.drop_table('attachments')
    op.drop_table('app_state')
    op.drop_table('adjustment_accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
