"""Application contracts and pure semantic core for Everyday Entry Gateway."""

from .account_resolver import AccountResolution, AccountUse, EntryAccount
from .amounts import (
    EntryAsset,
    NormalizedAmount,
    normalize_amount,
    validate_amount_source_consistency,
)
from .category_resolver import (
    CategoryResolution,
    CategoryUsageKind,
    EntryCategory,
)
from .compiler import (
    EntryCompilationContext,
    OriginalCategoryAllocation,
    OriginalEntry,
    compile_entry,
)
from .duplicate_detector import (
    DuplicateCandidate,
    DuplicateDecision,
    DuplicateEvidenceKind,
    decide_duplicate,
)
from .contracts import (
    AccountRef,
    AdjustmentEntryInput,
    BalanceInput,
    CategoryAllocationInput,
    CategoryRef,
    Clarification,
    ClarificationChoice,
    CommitEntryInput,
    CommittedEntry,
    CreditCardPaymentEntryInput,
    EntryPreview,
    EntryNarrativeInput,
    EntryWarning,
    EntryWarningCode,
    EverydayEntryInput,
    EverydayEntryService,
    ExternalReferenceInput,
    ExternalReferenceKind,
    ExpenseEntryInput,
    IncomeEntryInput,
    MoneyInput,
    MoneyDenomination,
    PreparedEntry,
    PreparedEntryStatus,
    PreviewAccount,
    PreviewMoney,
    RefundEntryInput,
    ResolvedEntryReferences,
    TransferEntryInput,
)
from .errors import EntryClarificationRequired, EntryErrorCode, EntryGatewayError

__all__ = [
    "AccountRef",
    "AccountResolution",
    "AccountUse",
    "AdjustmentEntryInput",
    "BalanceInput",
    "CategoryAllocationInput",
    "CategoryRef",
    "CategoryResolution",
    "CategoryUsageKind",
    "Clarification",
    "ClarificationChoice",
    "CommitEntryInput",
    "CommittedEntry",
    "CreditCardPaymentEntryInput",
    "DuplicateCandidate",
    "DuplicateDecision",
    "DuplicateEvidenceKind",
    "EntryAccount",
    "EntryAsset",
    "EntryCategory",
    "EntryClarificationRequired",
    "EntryCompilationContext",
    "EntryErrorCode",
    "EntryGatewayError",
    "EntryNarrativeInput",
    "EntryPreview",
    "EntryWarning",
    "EntryWarningCode",
    "EverydayEntryInput",
    "EverydayEntryService",
    "ExpenseEntryInput",
    "ExternalReferenceInput",
    "ExternalReferenceKind",
    "IncomeEntryInput",
    "MoneyDenomination",
    "MoneyInput",
    "NormalizedAmount",
    "OriginalCategoryAllocation",
    "OriginalEntry",
    "PreparedEntry",
    "PreparedEntryStatus",
    "PreviewAccount",
    "PreviewMoney",
    "RefundEntryInput",
    "ResolvedEntryReferences",
    "TransferEntryInput",
    "compile_entry",
    "decide_duplicate",
    "normalize_amount",
    "validate_amount_source_consistency",
]
