SELECT
    (SELECT version_num FROM public.alembic_version) AS source_revision,
    CAST(to_regclass('public.attachments') AS text) AS attachments_relation,
    (SELECT count(*) FROM public.attachments) AS attachments_count,
    (SELECT count(*) FROM public.accounts) AS accounts_count,
    (SELECT count(*) FROM public.accounts WHERE book_id IS DISTINCT FROM :source_book_id) AS accounts_foreign_count,
    (SELECT count(*) FROM public.assets) AS assets_count,
    (SELECT count(*) FROM public.categories) AS categories_count,
    (SELECT count(*) FROM public.categories WHERE book_id IS DISTINCT FROM :source_book_id) AS categories_foreign_count,
    (SELECT count(*) FROM public.category_versions) AS category_versions_count,
    (SELECT count(*) FROM public.category_versions WHERE book_id IS DISTINCT FROM :source_book_id) AS category_versions_foreign_count,
    (SELECT count(*) FROM public.classification_events) AS classification_events_count,
    (SELECT count(*) FROM public.classification_events WHERE book_id IS DISTINCT FROM :source_book_id) AS classification_events_foreign_count,
    (SELECT count(*) FROM public.counterparties) AS counterparties_count,
    (SELECT count(*) FROM public.counterparties WHERE book_id IS DISTINCT FROM :source_book_id) AS counterparties_foreign_count,
    (SELECT count(*) FROM public.investment_events) AS investment_events_count,
    (SELECT count(*) FROM public.investment_events WHERE book_id IS DISTINCT FROM :source_book_id) AS investment_events_foreign_count,
    (SELECT count(*) FROM public.investment_valuations) AS investment_valuations_count,
    (SELECT count(*) FROM public.investment_valuations WHERE book_id IS DISTINCT FROM :source_book_id) AS investment_valuations_foreign_count,
    (SELECT count(*) FROM public.ledger_books) AS ledger_books_count,
    (SELECT count(*) FROM public.postings) AS postings_count,
    (SELECT count(*) FROM public.postings WHERE book_id IS DISTINCT FROM :source_book_id) AS postings_foreign_count,
    (SELECT count(*) FROM public.transaction_lines) AS transaction_lines_count,
    (SELECT count(*) FROM public.transaction_lines WHERE book_id IS DISTINCT FROM :source_book_id) AS transaction_lines_foreign_count,
    (SELECT count(*) FROM public.transactions) AS transactions_count,
    (SELECT count(*) FROM public.transactions WHERE book_id IS DISTINCT FROM :source_book_id) AS transactions_foreign_count
