from __future__ import annotations


EXIT_SUCCESS = 0
EXIT_VALIDATION = 2
EXIT_POLICY_DENIED = 3
EXIT_IDEMPOTENCY_CONFLICT = 4
EXIT_STALE_VERSION = 5
EXIT_AUTH = 6
EXIT_SECURITY_PRECONDITION = 7
EXIT_NOT_FOUND = 8
