from __future__ import annotations

import argparse
import os

from .parser_recurring import add_recurring_parser


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ta")
    parser.add_argument("--base-url", default=os.getenv("TRACK_ANYWHERE_API", "http://localhost:8000"))
    parser.add_argument("--token", default=None, help="Bearer token. Prefer OS keyring; this is for one-shot use.")
    parser.add_argument("--insecure-automation", action="store_true", help="Allow env-token automation with warning.")
    sub = parser.add_subparsers(dest="command", required=True)

    login = sub.add_parser("login")
    login.add_argument("token")

    auth = sub.add_parser("auth")
    auth_sub = auth.add_subparsers(dest="auth_command", required=True)
    auth_login = auth_sub.add_parser("login")
    auth_login.add_argument("token")
    auth_dev = auth_sub.add_parser("dev-token")
    auth_dev.add_argument("--json", action="store_true")
    auth_status = auth_sub.add_parser("status")
    auth_status.add_argument("--json", action="store_true")

    data = sub.add_parser("data")
    data_sub = data.add_subparsers(dest="data_command", required=True)
    data_backup = data_sub.add_parser("backup")
    data_backup.add_argument("--database-url", default=None)
    data_backup.add_argument("--output-dir")
    data_backup.add_argument("--label")
    data_backup.add_argument("--json", action="store_true")

    summary = sub.add_parser("summary")
    summary_sub = summary.add_subparsers(dest="summary_command", required=True)
    summary_accounts = summary_sub.add_parser("accounts")
    summary_accounts.add_argument("--group-by", default="subtype")
    summary_accounts.add_argument("--currency")
    summary_accounts.add_argument("--institution-type")
    summary_accounts.add_argument("--include-system", action="store_true")
    summary_accounts.add_argument("--json", action="store_true")
    summary_categories = summary_sub.add_parser("categories")
    summary_categories.add_argument("--kind", choices=("income", "expense"))
    summary_categories.add_argument("--currency")
    summary_categories.add_argument("--json", action="store_true")

    investment = sub.add_parser("investment")
    investment_sub = investment.add_subparsers(dest="investment_command", required=True)
    investment_event = investment_sub.add_parser("event")
    investment_event.add_argument("account_id")
    investment_event.add_argument("--type", dest="event_type", choices=("buy", "add", "sell", "income"), required=True)
    investment_event.add_argument("--amount", required=True)
    investment_event.add_argument("--currency", default="CNY")
    investment_event.add_argument("--occurred-at")
    investment_event.add_argument("--memo")
    investment_event.add_argument("--units")
    investment_event.add_argument("--nav")
    investment_event.add_argument("--idempotency-key")
    investment_event.add_argument("--json", action="store_true")
    investment_performance = investment_sub.add_parser("performance")
    investment_performance.add_argument("account_id")
    investment_performance.add_argument("--as-of")
    investment_performance.add_argument("--json", action="store_true")

    user_group = sub.add_parser("user")
    user_sub = user_group.add_subparsers(dest="user_command", required=True)
    user_create = user_sub.add_parser("create")
    user_create.add_argument("username")
    user_create.add_argument("--display-name")
    user_create.add_argument("--idempotency-key")
    user_create.add_argument("--json", action="store_true")
    user_list = user_sub.add_parser("list")
    user_list.add_argument("--json", action="store_true")

    category_group = sub.add_parser("category")
    category_sub = category_group.add_subparsers(dest="category_command", required=True)
    category_create = category_sub.add_parser("create")
    category_create.add_argument("--kind", choices=("income", "expense"), required=True)
    category_create.add_argument("--primary", required=True)
    category_create.add_argument("--secondary")
    category_create.add_argument("--idempotency-key")
    category_create.add_argument("--json", action="store_true")
    category_list = category_sub.add_parser("list")
    category_list.add_argument("--kind", choices=("income", "expense"))
    category_list.add_argument("--primary")
    category_list.add_argument("--secondary")
    category_list.add_argument("--json", action="store_true")
    category_find = category_sub.add_parser("find")
    category_find.add_argument("--kind", choices=("income", "expense"), required=True)
    category_find.add_argument("--primary", required=True)
    category_find.add_argument("--secondary")
    category_find.add_argument("--json", action="store_true")
    category_show = category_sub.add_parser("show")
    category_show.add_argument("category_id")
    category_show.add_argument("--json", action="store_true")

    credit_card_group = sub.add_parser("credit-card")
    credit_card_sub = credit_card_group.add_subparsers(dest="credit_card_command", required=True)
    credit_card_list = credit_card_sub.add_parser("list")
    credit_card_list.add_argument("--json", action="store_true")
    credit_card_show = credit_card_sub.add_parser("show")
    credit_card_show.add_argument("account_id")
    credit_card_show.add_argument("--json", action="store_true")
    credit_card_update = credit_card_sub.add_parser("update")
    credit_card_update.add_argument("account_id")
    credit_card_update.add_argument("--credit-limit")
    credit_card_update.add_argument("--available-credit")
    credit_card_update.add_argument("--statement-day", type=int)
    credit_card_update.add_argument("--due-day", type=int)
    credit_card_update.add_argument("--annual-fee")
    credit_card_update.add_argument("--idempotency-key")
    credit_card_update.add_argument("--json", action="store_true")

    account_group = sub.add_parser("account")
    account_sub = account_group.add_subparsers(dest="account_command", required=True)
    account_create = account_sub.add_parser("create")
    account_create.add_argument("name")
    account_create.add_argument("--type", default="asset")
    account_create.add_argument("--currency", default="CNY")
    account_create.add_argument("--opening-balance", default="0")
    account_create.add_argument("--institution-type")
    account_create.add_argument("--subtype")
    account_create.add_argument("--institution")
    account_create.add_argument("--idempotency-key")
    account_create.add_argument("--json", action="store_true")
    account_list = account_sub.add_parser("list")
    account_list.add_argument("--name")
    account_list.add_argument("--type")
    account_list.add_argument("--currency")
    account_list.add_argument("--institution-type")
    account_list.add_argument("--subtype")
    account_list.add_argument("--institution")
    account_list.add_argument("--json", action="store_true")
    account_find = account_sub.add_parser("find")
    account_find.add_argument("--name", required=True)
    account_find.add_argument("--type")
    account_find.add_argument("--currency")
    account_find.add_argument("--institution-type")
    account_find.add_argument("--subtype")
    account_find.add_argument("--institution")
    account_find.add_argument("--json", action="store_true")
    account_show = account_sub.add_parser("show")
    account_show.add_argument("account_id")
    account_show.add_argument("--json", action="store_true")
    account_update = account_sub.add_parser("update")
    account_update.add_argument("account_id")
    account_update.add_argument("--institution-type")
    account_update.add_argument("--subtype")
    account_update.add_argument("--institution")
    account_update.add_argument("--idempotency-key")
    account_update.add_argument("--json", action="store_true")
    account_balance = account_sub.add_parser("balance")
    account_balance.add_argument("account_id")
    account_balance.add_argument("--include-drafts", action="store_true")
    account_balance.add_argument("--json", action="store_true")
    account_adjust = account_sub.add_parser("adjust")
    account_adjust.add_argument("account_id")
    account_adjust.add_argument("--amount", required=True, help="Delta to apply to the account balance; negative values decrease it.")
    account_adjust.add_argument("--purpose", required=True)
    account_adjust.add_argument("--occurred-at")
    account_adjust.add_argument("--currency", default="CNY")
    account_adjust.add_argument("--idempotency-key")
    account_adjust.add_argument("--json", action="store_true")

    account = sub.add_parser("account-create")
    account.add_argument("name")
    account.add_argument("--type", default="asset")
    account.add_argument("--currency", default="CNY")
    account.add_argument("--opening-balance", default="0")
    account.add_argument("--institution-type")
    account.add_argument("--subtype")
    account.add_argument("--institution")
    account.add_argument("--idempotency-key")
    account.add_argument("--json", action="store_true")

    capture = sub.add_parser("capture")
    capture.add_argument("memo")
    capture.add_argument("--amount", type=str)
    capture.add_argument("--source-account-id")
    capture.add_argument("--expense-account-id")
    capture.add_argument("--currency", default="CNY")
    capture.add_argument("--idempotency-key")
    capture.add_argument("--dry-run", action="store_true")
    capture.add_argument("--json", action="store_true")

    confirm = sub.add_parser("draft-confirm")
    confirm.add_argument("draft_id")
    confirm.add_argument("--expected-version", type=int, required=True)
    confirm.add_argument("--idempotency-key")
    confirm.add_argument("--json", action="store_true")

    tx = sub.add_parser("tx")
    tx_sub = tx.add_subparsers(dest="tx_command", required=True)
    tx_record = tx_sub.add_parser("record")
    tx_record.add_argument("--amount", required=True)
    tx_record.add_argument("--from-account-id", "--from", dest="from_account_id", required=True)
    tx_record.add_argument("--to-account-id", "--to", dest="to_account_id", required=True)
    tx_record.add_argument("--purpose", required=True)
    tx_record.add_argument("--occurred-at")
    tx_record.add_argument("--currency", default="CNY")
    tx_record.add_argument("--category-id")
    tx_record.add_argument("--idempotency-key")
    tx_record.add_argument("--json", action="store_true")
    tx_list = tx_sub.add_parser("list")
    tx_list.add_argument("--account-id")
    tx_list.add_argument("--category-id")
    tx_list.add_argument("--limit", type=int, default=20)
    tx_list.add_argument("--json", action="store_true")
    tx_show = tx_sub.add_parser("show")
    tx_show.add_argument("transaction_id")
    tx_show.add_argument("--json", action="store_true")
    tx_reverse = tx_sub.add_parser("reverse")
    tx_reverse.add_argument("transaction_id")
    tx_reverse.add_argument("--memo", required=True)
    tx_reverse.add_argument("--idempotency-key")
    tx_reverse.add_argument("--json", action="store_true")

    record = sub.add_parser("record")
    record.add_argument("--amount", required=True)
    record.add_argument("--from-account-id", "--from", dest="from_account_id", required=True)
    record.add_argument("--to-account-id", "--to", dest="to_account_id", required=True)
    record.add_argument("--purpose", required=True)
    record.add_argument("--occurred-at")
    record.add_argument("--currency", default="CNY")
    record.add_argument("--category-id")
    record.add_argument("--idempotency-key")
    record.add_argument("--json", action="store_true")

    expense = sub.add_parser("expense")
    expense_sub = expense.add_subparsers(dest="expense_command", required=True)
    expense_record = expense_sub.add_parser("record")
    expense_record.add_argument("--amount", required=True)
    expense_record.add_argument("--from-account-id", "--from", dest="from_account_id", required=True)
    expense_record.add_argument("--category-id", required=True)
    expense_record.add_argument("--purpose", required=True)
    expense_record.add_argument("--occurred-at")
    expense_record.add_argument("--currency", default="CNY")
    expense_record.add_argument("--idempotency-key")
    expense_record.add_argument("--json", action="store_true")

    income = sub.add_parser("income")
    income_sub = income.add_subparsers(dest="income_command", required=True)
    income_record = income_sub.add_parser("record")
    income_record.add_argument("--amount", required=True)
    income_record.add_argument("--to-account-id", "--to", dest="to_account_id", required=True)
    income_record.add_argument("--category-id", required=True)
    income_record.add_argument("--purpose", required=True)
    income_record.add_argument("--occurred-at")
    income_record.add_argument("--currency", default="CNY")
    income_record.add_argument("--idempotency-key")
    income_record.add_argument("--json", action="store_true")

    add_recurring_parser(sub)

    balance_adjust = sub.add_parser("balance-adjust")
    balance_adjust.add_argument("account_id")
    balance_adjust.add_argument("--amount", required=True, help="Delta to apply to the account balance; negative values decrease it.")
    balance_adjust.add_argument("--purpose", required=True)
    balance_adjust.add_argument("--occurred-at")
    balance_adjust.add_argument("--currency", default="CNY")
    balance_adjust.add_argument("--idempotency-key")
    balance_adjust.add_argument("--json", action="store_true")

    query = sub.add_parser("balance")
    query.add_argument("account_id")
    query.add_argument("--include-drafts", action="store_true")
    query.add_argument("--json", action="store_true")
    return parser
